---
- name: ufw disable
  command: ufw disable
  when: ufw is defined

- name: Install Firewalld
  apt: 
    name: firewalld 
    state: present

- name: unmask Firewalld
  command: systemctl unmask firewalld

- name: Firewalld service state
  service: 
    name: firewalld 
    state: started 
    enabled: yes
